name: thirds

description: >-
  SHA-3, BLAKE3, and EdDSA/Ed448 implementations in Dart,
  with EdDSA/Ed448 JWT support

version: 0.2.0-alpha.1

environment:
  sdk: '>=2.16.0 <3.0.0'

repository: https://github.com/mnito/thirds
dev_dependencies: 
  node_preamble: ^2.0.1
